### ISSUE TITLE
Support bbPress posts

### ISSUE THREAD

**Issue by flowdee** [flowdee/hearthstone-cards-for-wordpress#15]

**Comment by MedianP** [comment]
Hi ! Is this issue going to be fixed in the next update ? Thank you.

**Comment by flowdee** [comment]
This will be included in a future release for sure. But I can't make any promises now.

**Comment by flowdee** [comment]
bbPress is supported by the pro version of the plugin. http://coder.flowdee.de/hearthstone-cards-for-wordpress/
