### ISSUE TITLE
Cards with apostrophe not showing

### ISSUE THREAD

**Issue by antonisjk** [flowdee/hearthstone-cards-for-wordpress#17]
Hello, I have an issue with some cards that are not showing in my website. It seems that any card has an apostrophe, has problem.
For example the Sen'Jin Shielmasta is not showing. Here's a picture with some of them:

![screenshot - 21012015 - 03 06 56](https://cloud.githubusercontent.com/assets/10629665/5836495/53e475be-a17f-11e4-8d74-5f526c2bf655.png)

**Comment by flowdee** [comment]
Hey antonisjk,

I fixed this bug yesterday and the new update v1.5.1 will be available on Friday.

https://github.com/flowdee/hearthstone-cards-for-wordpress/issues/16
