### ISSUE TITLE
Error on update 1.5.3

### ISSUE THREAD

**Issue by klangwiedergabe** [flowdee/hearthstone-cards-for-wordpress#18]
Spanish cards are not shown and it says.

Warning: file_get_contents() [function.file-get-contents]: http:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/animalli/public_html/hearthstone.cl/wp-content/plugins/hearthstone-cards/includes/functions.php on line 70

Warning: file_get_contents(http://hearthstone.cl/wp-content/plugins/hearthstone-cards/includes/lib/AllSets.esES.json) [function.file-get-contents]: failed to open stream: no suitable wrapper could be found in /home/animalli/public_html/hearthstone.cl/wp-content/plugins/hearthstone-cards/includes/functions.php on line 70

**Comment by flowdee** [comment]
Did it work before you updated?
Did you change anything on your webserver?

In fact the update didn't change anything according to this function. Can you look if the file "AllSets.esES.json" is currently in your plugin /includes/lib/ folder?

**Comment by klangwiedergabe** [comment]
It was working fine before the update,
I didn't change anything on my server,
Yes, the file AllSets.esES.json is right there in the /includes/lib/ folder within the plugin.

**Comment by klangwiedergabe** [comment]
but I actually jump from version 1.5 to 1.5.3
I never had the 1.5.1

Anyway I uninstall the plugin completely and then I installed again, but the same error is shown.

**Comment by flowdee** [comment]
Just to be sure can you please make a check using the english language?
