### ISSUE TITLE
Missing / wrong Card detection (English version)

### ISSUE THREAD

**Issue by flowdee** [flowdee/hearthstone-cards-for-wordpress#2]
- Sen’jin Shieldmasta (won't be linked)
- Druid of the Claw (only "Claw" linked
- "Nerub’ar Weblord" won't link
- "Dreamhack" will link the"Dream"
- Imprescindible

Demo: http://pedromancheno.com/soulstriderx/?p=6

**Comment by antonisjk** [comment]
Sen’jin Shieldmaster still is not working...

![screenshot - 21012015 - 12 44 44](https://cloud.githubusercontent.com/assets/10629665/5834957/88871470-a16b-11e4-9ead-deff6cb7a292.png)

**Comment by flowdee** [comment]
According to the other issue you opened the problem is fixed right now and the update will be available at the end of the week.
