### ISSUE TITLE
Add in new Blackrock Mountain Cards

### ISSUE THREAD

**Issue by Vastidious** [flowdee/hearthstone-cards-for-wordpress#20]
Would love to have the new Blackrock Mountain cards added in the system. So far there are about 7 cards but there will be 31 new cards shortly. And if you would like to know, I am using the plugin on www.legendoftheinnkeeper.com for our podcast. It's awesome!

**Comment by flowdee** [comment]
Hey @Vastidious thanks for your message!

Sure I'll add the cards as soon as possible. The plugin is based on the database of http://hearthstonejson.com/ and I'm waiting for the card updates right now.

Just be patient :)

**Comment by Vastidious** [comment]
Awesome! Glad to wait it out. I'll also send you a little something to
support the project. Plus if you want to use us as an example of
implementation feel free.  I'll add a note on the site that references back
to your plugin if you like.

On Mon, Mar 16, 2015 at 4:58 PM, flowdee <notifications@github.com> wrote:

> Hey @Vastidious <https://github.com/Vastidious> thanks for your message!
>
> Sure I'll add the cards as soon as possible. The plugin is based on the
> database of http://hearthstonejson.com/ and I'm waiting for the card
> updates right now.
>
> Just be patient :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flowdee/hearthstone-cards-for-wordpress/issues/20#issuecomment-81935811>
> .
>



-- 
Steve Eason
godlydad@gmail.com

**Comment by flowdee** [comment]
Glad to hear, thanks dude!

Already added you to the demo page: http://coder.flowdee.de/hearthstone-cards-for-wordpress/demo/

My Bluepost Plugin might be something for you too? http://coder.flowdee.de/blueposts-for-wordpress/demo/

**Comment by Vastidious** [comment]
I was really thinking about using it. I'll take a closer look and see about
implementing that as well.

Thanks!

On Mon, Mar 16, 2015 at 5:05 PM, flowdee <notifications@github.com> wrote:

> Glad to hear, thanks dude!
>
> Already added you to the demo page:
> http://coder.flowdee.de/hearthstone-cards-for-wordpress/demo/
>
> My Bluepost Plugin might be something for you too?
> http://coder.flowdee.de/blueposts-for-wordpress/demo/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flowdee/hearthstone-cards-for-wordpress/issues/20#issuecomment-81938372>
> .
>



-- 
Steve Eason
godlydad@gmail.com

**Comment by Vastidious** [comment]
Since I do have your ear, I do have one item that doesn't work well with
the plugin and it's not likely something you can fix. Just wanted you to be
aware of. When I paste text in from notepad and publish it when a card name
has an ' in the title, the plugin doesn't like that specific '.  I then
have to go back to the post and delete the ' and add it back in using the
WordPress editor and then it's happy. It's odd behavior but just something
I've had to work around.

And I saw that you already had a suggestion to add [The Coin] as an option
on Github. That would be nice to have. I have taught my co-hosts to add []
around all our card names (and to spell them correctly with proper
capitalization) however one of the always adds brackets around The Coin and
the plugin doesn't know what to do with it.

Thanks again!

On Mon, Mar 16, 2015 at 5:06 PM, Steve Eason <godlydad@gmail.com> wrote:

> I was really thinking about using it. I'll take a closer look and see
> about implementing that as well.
>
> Thanks!
>
> On Mon, Mar 16, 2015 at 5:05 PM, flowdee <notifications@github.com> wrote:
>
>> Glad to hear, thanks dude!
>>
>> Already added you to the demo page:
>> http://coder.flowdee.de/hearthstone-cards-for-wordpress/demo/
>>
>> My Bluepost Plugin might be something for you too?
>> http://coder.flowdee.de/blueposts-for-wordpress/demo/
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/flowdee/hearthstone-cards-for-wordpress/issues/20#issuecomment-81938372>
>> .
>>
>
>
>
> --
> Steve Eason
> godlydad@gmail.com
>



-- 
Steve Eason
godlydad@gmail.com

**Comment by Vastidious** [comment]
I just sent over a donation using Paypal. Hope that helps! Thanks again.

On Mon, Mar 16, 2015 at 5:10 PM, Steve Eason <godlydad@gmail.com> wrote:

> Since I do have your ear, I do have one item that doesn't work well with
> the plugin and it's not likely something you can fix. Just wanted you to be
> aware of. When I paste text in from notepad and publish it when a card name
> has an ' in the title, the plugin doesn't like that specific '.  I then
> have to go back to the post and delete the ' and add it back in using the
> WordPress editor and then it's happy. It's odd behavior but just something
> I've had to work around.
>
> And I saw that you already had a suggestion to add [The Coin] as an option
> on Github. That would be nice to have. I have taught my co-hosts to add []
> around all our card names (and to spell them correctly with proper
> capitalization) however one of the always adds brackets around The Coin and
> the plugin doesn't know what to do with it.
>
> Thanks again!
>
> On Mon, Mar 16, 2015 at 5:06 PM, Steve Eason <godlydad@gmail.com> wrote:
>
>> I was really thinking about using it. I'll take a closer look and see
>> about implementing that as well.
>>
>> Thanks!
>>
>> On Mon, Mar 16, 2015 at 5:05 PM, flowdee <notifications@github.com>
>> wrote:
>>
>>> Glad to hear, thanks dude!
>>>
>>> Already added you to the demo page:
>>> http://coder.flowdee.de/hearthstone-cards-for-wordpress/demo/
>>>
>>> My Bluepost Plugin might be something for you too?
>>> http://coder.flowdee.de/blueposts-for-wordpress/demo/
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/flowdee/hearthstone-cards-for-wordpress/issues/20#issuecomment-81938372>
>>> .
>>>
>>
>>
>>
>> --
>> Steve Eason
>> godlydad@gmail.com
>>
>
>
>
> --
> Steve Eason
> godlydad@gmail.com
>



-- 
Steve Eason
godlydad@gmail.com

**Comment by flowdee** [comment]
thanks again!

going to update this issue as soon as the new cards are available

**Comment by flowdee** [comment]
FYI: The Blackrock card update will be released short after 9th April 2015.

**Comment by flowdee** [comment]
The Blackrock Mountain update is available now on your WordPress dashboard. Enjoy! ;-)
