### ISSUE TITLE
Apostrophe issue

### ISSUE THREAD

**Issue by AsphyxX** [flowdee/hearthstone-cards-for-wordpress#21]
Hey,

noticed a bug when I tried to include [Mal'Ganis] in my post : the apostrophe won't let me.

I'm using 1.5.3

**Comment by flowdee** [comment]
Hey AsphyxX, I tested it on my demo page and it works fine with this card: http://coder.flowdee.de/hearthstone-cards-for-wordpress/demo/

Can you give me a link to your website? Your editor might inserted a wrong apostrophe?
