### ISSUE TITLE
will you support zhCN  card language ?

### ISSUE THREAD

**Issue by everchump** [flowdee/hearthstone-cards-for-wordpress#25]
it's great，but my language is zhCN，will you support it ?

thanks.

**Comment by flowdee** [comment]
Hey everchump,

right now the plugin is based on the database of hearthhead.com which does not support Chinese. I'm sorry.

Do you know a chinese page hosting card images? Then I might be able to integrate it too.

**Comment by everchump** [comment]
1,[http://www.hearthstone.com.cn/cards/builder/](http://www.hearthstone.com.cn/cards/builder/)

it's a official website,url of Ancient Watcher is [http://hearthstone.nos.netease.com/1/l-cards/cards/neutral/Ancient+Watcher.png](http://hearthstone.nos.netease.com/1/l-cards/cards/neutral/Ancient+Watcher.png)

but the database is not updated.


2,[http://db.h.163.com/](http://db.h.163.com/)

pic url [http://img3.cache.netease.com/game/hs/db/cards/20141209/medium/EX1_002.png](http://img3.cache.netease.com/game/hs/db/cards/20141209/medium/EX1_002.png) for example.

163.com is the parter of blizzard in china,but the database is updated to V2.5.0.8416.

3,[http://db.178.com/wow/cn/hscards.html](http://db.178.com/wow/cn/hscards.html)

pic url [http://img.db.178.com/wow/icons/hs/cardimage/BRM_027.png](http://img.db.178.com/wow/icons/hs/cardimage/BRM_027.png) for example.

**Comment by flowdee** [comment]
Thanks for your help @everchump! I'll take a look into. Due to the fact that right now the plugin is not made for the case, that different image databases are used, please let me some time to figure out how it's the best way to implement this. Thanks :)

**Comment by flowdee** [comment]
@everchump http://cn.hearthhead.com/card=36/cenarius are these the right ones?

**Comment by everchump** [comment]
yes，it's right.
