### ISSUE TITLE
golden cards in german language

### ISSUE THREAD

**Issue by sebako86** [flowdee/hearthstone-cards-for-wordpress#26]
Hey there,

I  cannot make the golden cards in german language to work. Can you give me a hint if that's implemented?

Cheers,

Seb

**Comment by flowdee** [comment]
Hey @sebako86,

works as for the english one: 
```
[Naxxramasschemen gold]
```
![Naxxramasschemen](http://fs1.directupload.net/images/150721/gblua7oe.png)

**Comment by sebako86** [comment]
ah lowercase, that was it. :)
Thanks.

**Comment by flowdee** [comment]
hehe fine :)
