### ISSUE TITLE
Cards with apostrophe still not showing

### ISSUE THREAD

**Issue by jimarasss1** [flowdee/hearthstone-cards-for-wordpress#28]
All cards working perfectly ,except cards with apostrophe

**Comment by flowdee** [comment]
@jimarasss1 please gimme explicit examples. As you can see on the demo they are working if written correctly including the right apostrophe. https://coder.flowdee.de/hearthstone-cards-for-wordpress/demo/

**Comment by jimarasss1** [comment]
http://prntscr.com/8clzpy Something like this :P

**Comment by flowdee** [comment]
As you can see on my demo page, Kel'Thuzad is definitely working if you use the correct apostrophe.

I can't read the russian one if it's a card name. In this case please give me the english card name so I can test the russian one on my own.

**Comment by flowdee** [comment]
@jimarasss1 did you get it working?
