### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by fbrevoort** [flowdee/hearthstone-cards-for-wordpress#39]
Hi these links doesn't seem to convert, 

[Chillwind Yeti] 
[Boulderfist Ogre]
[Bloodfen Raptor]

**Comment by fbrevoort** [comment]
also
[Assassin's Blade]

**Comment by fbrevoort** [comment]
[Murloc Raider]
[Murloc Tinyfin]

**Comment by fbrevoort** [comment]
[Fiery War Axe]
[Arcanite Reaper]

**Comment by flowdee** [comment]
Hey @fbrevoort thanks for reporting. I'll check it. Think it's a general problem and not card related, but your examples help!

**Comment by flowdee** [comment]
Released an update which fixes the issue. Please take a look and thanks for reporting! :+1:
