### ISSUE TITLE
Tooltip issue (see screenshot) 

### ISSUE THREAD

**Issue by fbrevoort** [flowdee/hearthstone-cards-for-wordpress#41]
![capture](https://cloud.githubusercontent.com/assets/45795/13967740/a472ac5e-f0dd-11e5-8974-e5ea590b7a14.jpg)

the tooltip image gets cut off if I use the links inside a feature box for my theme, I'm pretty sure the feature box is not an iframe.

**Comment by flowdee** [comment]
the problem is that your theme uses overflow hidden for the container and that's why it has no chance to be displayed correctly. Please take a look into the css. If you can't find it feel free to send me the link and I will assist.

**Comment by fbrevoort** [comment]
thank you for your help :), here is the link
http://www.dugihearthstone.com/decks/druid/classic-druid/

**Comment by flowdee** [comment]
`.feature-box { overflow: visible !important; }`

should do the trick :+1:

**Comment by fbrevoort** [comment]
that did it, thank you very much
